const UserGroupActionTypes = {
    CREATE_USERGROUP: 'CREATE_USERGROUP',
    GET_USERGROUP: 'GET_USERGROUP',
    UPDATE_USERGROUP: 'UPDATE_USERGROUP',
    DELETE_USERGROUP: 'DELETE_USERGROUP'
};

export default UserGroupActionTypes;